### ISSUE TITLE
pip install doesn't download data folders

### ISSUE THREAD

**Issue by daniellabardalezgagliuffi** [hover2pi/sedkit#54]
I ran
pip install sedkit
on a conda environment with python 3.7, and it successfully installs it:
Successfully installed sedkit-1.0.4

But then when I try to import SED from sedkit:

>>> from sedkit import SED
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/__init__.py", line 1, in <module>
    from .catalog import Catalog
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/catalog.py", line 23, in <module>
    from .sed import SED
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/sed.py", line 35, in <module>
    SptRadius = rel.SpectralTypeRadius()
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/relations.py", line 221, in __init__
    self.generate(orders)
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/relations.py", line 281, in generate
    afgk_data = ii.read(afgk, format='csv', comment='#')
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 304, in read
    dat = fast_reader_rdr.read(table)
  File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/fastbasic.py", line 117, in read
    **self.kwargs)
  File "astropy/io/ascii/cparser.pyx", line 235, in astropy.io.ascii.cparser.CParser.__cinit__
  File "astropy/io/ascii/cparser.pyx", line 277, in astropy.io.ascii.cparser.CParser.setup_tokenizer
  File "astropy/io/ascii/cparser.pyx", line 124, in astropy.io.ascii.cparser.FileString.__cinit__
**FileNotFoundError: [Errno 2] No such file or directory: '/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/data/AFGK_radii.txt'**

When I go to:

/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/

I see that there is no data folder, so indeed sedkit can't find the file because it's not there.

**Comment by hover2pi** [comment]
Good to know. Thanks Daniella! Looks like I need to fix the MANIFEST.in file.

- Joe

On May 8, 2020, at 11:12 AM, Daniella Bardalez Gagliuffi <notifications@github.com> wrote:

﻿

I ran
pip install sedkit
on a conda environment with python 3.7, and it successfully installs it:
Successfully installed sedkit-1.0.4

But then when I try to import SED from sedkit:

from sedkit import SED
Traceback (most recent call last):
File "", line 1, in
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/init.py", line 1, in
from .catalog import Catalog
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/catalog.py", line 23, in
from .sed import SED
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/sed.py", line 35, in
SptRadius = rel.SpectralTypeRadius()
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/relations.py", line 221, in init
self.generate(orders)
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/relations.py", line 281, in generate
afgk_data = ii.read(afgk, format='csv', comment='#')
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/ui.py", line 304, in read
dat = fast_reader_rdr.read(table)
File "/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/astropy/io/ascii/fastbasic.py", line 117, in read
**self.kwargs)
File "astropy/io/ascii/cparser.pyx", line 235, in astropy.io.ascii.cparser.CParser.cinit
File "astropy/io/ascii/cparser.pyx", line 277, in astropy.io.ascii.cparser.CParser.setup_tokenizer
File "astropy/io/ascii/cparser.pyx", line 124, in astropy.io.ascii.cparser.FileString.cinit
FileNotFoundError: [Errno 2] No such file or directory: '/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/data/AFGK_radii.txt'

When I go to:

/Users/daniella/opt/anaconda3/lib/python3.7/site-packages/sedkit/

I see that there is no data folder, so indeed sedkit can't find the file because it's not there.

**Comment by hover2pi** [comment]
I think this is resolved in v1.0.8 @daniellabardalezgagliuffi . Let me know if the problem persists!
